[package]
name = "services"
version.workspace = true
edition.workspace = true

[dependencies]
gallery-core = { path = "../gallery-core" }
anyhow = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
rayon = "1.11.0"
async-trait = { workspace = true }
async-recursion = { workspace = true }
tokio = { version = "1", features = ["rt"] }


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1"

